"""
resolver.py — fetches track metadata (artist, title) via yt-dlp
without downloading the actual audio, and expands playlist URLs.

YouTube titles often look like:
  "Artist - Title (Official Video)"
  "Title ft. Artist2"
  "Just A Title"

The %(artist)s field is frequently empty for YouTube uploads, so we
apply a cascade of fallbacks:
  1. yt-dlp artist field
  2. Parse "Artist – Title" from the video title
  3. Strip " - Topic" from the uploader/channel name
  4. Leave artist empty (library check will fall back to title-only mode)
"""
from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass
from typing import Optional

# Matches "Artist - Title", "Artist – Title", "Artist — Title"
_SPLIT_RE = re.compile(r"^(.+?)\s*[-\u2013\u2014]\s*(.+)$")

# Noise suffixes to strip from titles
_NOISE_RE = re.compile(
    r"\s*[\(\[]"
    r"(?:official\s*(?:video|audio|music\s*video|lyric\s*video)?|"
    r"lyrics?|hq|hd|4k|remaster(?:ed)?|"
    r"(?:ft|feat)\.?\s+[^\)\]]+|"
    r"prod\.?\s+[^\)\]]+|"
    r"\d{4})"
    r"\s*[\)\]]",
    re.IGNORECASE,
)

_TOPIC_SUFFIX_RE = re.compile(r"\s*-\s*topic$", re.IGNORECASE)
_UNKNOWN_VALUES = {"na", "n/a", "various artists", "auto-generated by youtube", ""}


def _clean(s: str) -> str:
    """Strip noise phrases and normalise whitespace."""
    return _NOISE_RE.sub("", s).strip()


def _parse_artist_title(
    raw_title: str,
    artist_field: str,
    uploader: str,
) -> tuple[str, str]:
    """
    Returns (artist, title). Artist may be empty string if unknown.
    """
    title = _clean(raw_title)
    artist_lc = artist_field.strip().lower()

    # 1. Trust yt-dlp's artist field if it looks real
    if artist_field.strip() and artist_lc not in _UNKNOWN_VALUES:
        return artist_field.strip(), title

    # 2. Try splitting the cleaned title on " - "
    m = _SPLIT_RE.match(title)
    if m:
        candidate_artist = _clean(m.group(1))
        candidate_title = _clean(m.group(2))
        # Heuristic: artist part shouldn't be too long (avoids splitting on
        # titles that naturally contain dashes)
        if len(candidate_artist.split()) <= 5:
            return candidate_artist, candidate_title

    # 3. Use uploader/channel as artist, strip YouTube's " - Topic" suffix
    if uploader.strip() and uploader.strip().lower() not in _UNKNOWN_VALUES:
        artist = _TOPIC_SUFFIX_RE.sub("", uploader.strip())
        return artist.strip(), title

    # 4. No artist info available
    return "", title


@dataclass
class TrackMeta:
    url: str
    title: str
    artist: str
    raw_title: str  # original title string from yt-dlp, kept for debugging


def resolve_metadata(url: str, timeout: int = 30) -> Optional[TrackMeta]:
    """
    Query yt-dlp for track metadata without downloading.
    Returns None if the URL is unavailable or yt-dlp fails.
    """
    try:
        result = subprocess.run(
            [
                "yt-dlp",
                "--print", "%(artist)s|||%(title)s|||%(uploader)s",
                "--no-download",
                "--no-playlist",
                "--quiet",
                "--no-warnings",
                url,
            ],
            capture_output=True,
            text=True,
            timeout=timeout,
        )

        if result.returncode != 0:
            return None

        line = result.stdout.strip().splitlines()[0] if result.stdout.strip() else ""
        parts = line.split("|||")
        if len(parts) < 2:
            return None

        artist_field = parts[0].strip() if parts[0].strip() != "NA" else ""
        raw_title = parts[1].strip() if len(parts) > 1 else ""
        uploader = parts[2].strip() if len(parts) > 2 else ""

        if not raw_title:
            return None

        artist, title = _parse_artist_title(raw_title, artist_field, uploader)

        return TrackMeta(
            url=url,
            title=title,
            artist=artist,
            raw_title=raw_title,
        )

    except subprocess.TimeoutExpired:
        return None
    except Exception:
        return None


# ── Playlist expansion ────────────────────────────────────────────────────────

_PLAYLIST_RE = re.compile(r"[?&]list=|/playlist\?", re.IGNORECASE)


def is_playlist_url(url: str) -> bool:
    """Return True if the URL points to a YouTube (or similar) playlist."""
    return bool(_PLAYLIST_RE.search(url))


def expand_playlist(url: str, timeout: int = 60) -> list[str]:
    """
    Expand a playlist URL into individual video URLs using yt-dlp's
    flat-playlist mode (no downloads, just URL enumeration).

    Returns a list of individual video URLs.
    Falls back to [url] (treating it as a single track) if expansion fails.
    """
    try:
        result = subprocess.run(
            [
                "yt-dlp",
                "--flat-playlist",
                "--print", "url",
                "--quiet",
                "--no-warnings",
                url,
            ],
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        if result.returncode != 0:
            return [url]
        urls = [line.strip() for line in result.stdout.splitlines() if line.strip()]
        return urls if urls else [url]
    except Exception:
        return [url]
